import Foundation
import ComposableArchitecture

@DependencyClient
struct AviationEventsClient {
    var loadCurrentEvents: @Sendable () async throws -> [AviationEvent]
    var loadFAIChampionships: @Sendable () async throws -> [AviationEvent]
    var loadAllEvents: @Sendable () async throws -> [AviationEvent]
}

extension DependencyValues {
    var aviationEventsClient: AviationEventsClient {
        get { self[AviationEventsClient.self] }
        set { self[AviationEventsClient.self] = newValue }
    }
}

extension AviationEventsClient: DependencyKey {
    static let liveValue = Self(
        loadCurrentEvents: {
            return AviationEventsClient.mockCurrentEvents
        },
        loadFAIChampionships: {
            return AviationEventsClient.mockFAIChampionships
        },
        loadAllEvents: {
            return AviationEventsClient.mockAllEvents
        }
    )
    
    static let testValue = Self(
        loadCurrentEvents: { [] },
        loadFAIChampionships: { [] },
        loadAllEvents: { [] }
    )
}

extension AviationEventsClient {
    static let mockCurrentEvents: [AviationEvent] = [
        AviationEvent(
            id: "17267",
            title: "1st Autumn Championship of Kazakhstan for landing accuracy",
            location: "Taldykorgan",
            country: "KAZ",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 19)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 22)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Paragliding Accuracy",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://paragliding.kz",
            faiMiniSiteURL: "https://fai.org/events/17267",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "23 Sep - 14 Oct 2025"
        ),
        AviationEvent(
            id: "17302",
            title: "2025 PRISTA CUP F1E",
            location: "Alekovo",
            country: "BUL",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 19)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F1 - Free Flight - F1E (FF Slope Soaring Gliders), F1 - Free Flight - F1E (FF Slope Soaring Gliders) - Junior",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://aeromodelling.bg",
            faiMiniSiteURL: "https://fai.org/events/17302",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "26 Sep - 27 Sep 2025"
        ),
        AviationEvent(
            id: "17363",
            title: "2025 Olza Cup",
            location: "Český Těšín",
            country: "CZE",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 19)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "S - Space Models - S7 (Scale), S - Space Models - S4A (Boost Glider Duration - 0 to 2.5 Ns), S - Space Models - S6A (Streamer Duration - 0 to 2.5 Ns), S - Space Models - S9A (Gyrocopter Duration - 0 to 2.5 Ns), S - Space Models - S8P (RC Rocket Glider Time Duration and Precision Landing)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: nil,
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17739",
            title: "2025 Tribalj Open 2025",
            location: "Tribalj",
            country: "CRO",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 19)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Cross Country",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "26 Sep - 28 Sep 2025"
        ),
        AviationEvent(
            id: "17955",
            title: "WANDERBIRD Trophy - Kappl & See Paznaun",
            location: "Kappl",
            country: "AUT",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 19)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Hike & Fly",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17298",
            title: "2025 BULGARIA CUP F1E",
            location: "Alekovo",
            country: "BUL",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F1 - Free Flight - F1E (FF Slope Soaring Gliders), F1 - Free Flight - F1E (FF Slope Soaring Gliders) - Junior",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "27 Sep - 28 Sep 2025"
        ),
        AviationEvent(
            id: "17348",
            title: "2025 Zabokreky Cup",
            location: "Nadlice",
            country: "SVK",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F1 - Free Flight - F1A (FF Gliders), F1 - Free Flight - F1B (FF Wakefield), F1 - Free Flight - F1C (FF Aircraft with Piston Engines), F1 - Free Flight - F1Q (FF Electric Power Aircraft)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17436",
            title: "2025 27. Lippeweiden Pokal",
            location: "Luenen",
            country: "GER",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F3 - Radio Controlled Flight - F3B (RC Multi Task Gliders)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17507",
            title: "2025 1ª Coppa \"MADONNA di LORETO\"",
            location: "Recanati",
            country: "ITA",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F5 - Radio Controlled Electric Powered Flight - F5J (RC Electric Powered Thermal Duration Gliders)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "19 Apr - 20 Apr 2025"
        ),
        AviationEvent(
            id: "17510",
            title: "2025 Open Pikuinhas F5J 2025/Troféu Ibérico ,Contest Eurotour 2025",
            location: "Chamusca",
            country: "POR",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F5 - Radio Controlled Electric Powered Flight - F5J (RC Electric Powered Thermal Duration Gliders) - Senior",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17819",
            title: "2025 Rallye Toulouse Saint-Louis",
            location: "Toulouse - Saint Louis du Sénégal - Toulouse",
            country: "FRA",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 4)) ?? Date(),
            eventType: .secondCategory,
            sport: .generalAviation,
            discipline: "Rally Flying",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://rallye-toulouse-saintlouis.fr",
            faiMiniSiteURL: "https://fai.org/events/17819",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17938",
            title: "NISEKO SKY RALLY 2025",
            location: "Niseko",
            country: "JPN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 23)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Cross Country",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://niseko-sky-rally.jp",
            faiMiniSiteURL: "https://fai.org/events/17938",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17957",
            title: "Belli in Fly",
            location: "Locarno",
            country: "SUI",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Hike & Fly",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "21 Sep - 2025"
        ),
        AviationEvent(
            id: "17978",
            title: "6th II. LineUp Paragliding Accuracy Competition Hungarian National Championship",
            location: "Etyek",
            country: "HUN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 20)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Paragliding Accuracy",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "27 Sep - 28 Sep 2025"
        ),
        AviationEvent(
            id: "17349",
            title: "2025 Hogo Cup",
            location: "Nadlice",
            country: "SVK",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F1 - Free Flight - F1A (FF Gliders), F1 - Free Flight - F1B (FF Wakefield), F1 - Free Flight - F1C (FF Aircraft with Piston Engines), F1 - Free Flight - F1Q (FF Electric Power Aircraft)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17953",
            title: "IPXC Serie 3 - WEST JAVA PARAGLIDING CHAMPIONSHIP 2025",
            location: "Sumedang",
            country: "INA",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 21)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 28)) ?? Date(),
            eventType: .secondCategory,
            sport: .paragliding,
            discipline: "class 3 - Cross Country",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17974",
            title: "9th Telomoyo Cup IX 2025 - Hang Gliding",
            location: "salatiga",
            country: "INA",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 23)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 28)) ?? Date(),
            eventType: .secondCategory,
            sport: .hangGliding,
            discipline: "Sport Class - Cross Country",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17557",
            title: "2025 Shanghai Drone Racing World Cup",
            location: "Shanghai",
            country: "CHN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 24)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 27)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F9 - Drone Sport - F9U - Drone Racing",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://shanghai-drone-racing.cn",
            faiMiniSiteURL: "https://fai.org/events/17557",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: "24 Sep - 27 Sep 2025"
        ),
        AviationEvent(
            id: "17985",
            title: "International Karapınar XC Open Championship",
            location: "Karapınar / Konya",
            country: "TUR",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 24)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 28)) ?? Date(),
            eventType: .secondCategory,
            sport: .hangGliding,
            discipline: "class 1 - Cross country",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17469",
            title: "2025 USA Cup Spirit of St Louis",
            location: "St Louis, MO",
            country: "USA",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 25)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 9, day: 26)) ?? Date(),
            eventType: .other,
            sport: .aeromodelling,
            discipline: "F2 - Control Line Circular Flight - F2A (CL Speed), F2 - Control Line Circular Flight - F2G (CL Electric Speed)",
            classification: .cat2,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        )
    ]
    
    static let mockFAIChampionships: [AviationEvent] = [
        AviationEvent(
            id: "17786",
            title: "13th FAI World Paragliding Accuracy Championship",
            location: "Alanya, Antalya",
            country: "TUR",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 9)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 19)) ?? Date(),
            eventType: .worldChampionship,
            sport: .paragliding,
            discipline: "class 3 - Paragliding Accuracy",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://paragliding-accuracy-turkey.com",
            faiMiniSiteURL: "https://fai.org/events/17786",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17822",
            title: "1st FAI Asian Style and Accuracy Landing Championship",
            location: "Ji'an, Jiangxi Province",
            country: "CHN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 25)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 31)) ?? Date(),
            eventType: .continentalChampionship,
            sport: .skydiving,
            discipline: "Style and Accuracy Landing - Accuracy Landing, Style and Accuracy Landing - Style",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: "FAI mini-site",
            description: nil,
            documents: ["Bulletin 1 v2", "Bulletin 2"],
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17823",
            title: "16th FAI World Cup of Style and Accuracy Landing",
            location: "Ji'an, Jiangxi Province",
            country: "CHN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 25)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 10, day: 31)) ?? Date(),
            eventType: .other,
            sport: .skydiving,
            discipline: "Style and Accuracy Landing - Accuracy Landing, Style and Accuracy Landing - Style",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: "FAI mini-site",
            description: nil,
            documents: ["Bulletin 1 v2", "Bulletin 2"],
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17322",
            title: "47th CISM World Military Parachuting Championship",
            location: "Doha",
            country: "QAT",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 13)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 23)) ?? Date(),
            eventType: .worldChampionship,
            sport: .skydiving,
            discipline: "Style and Accuracy Landing - Accuracy Landing, Formation Skydiving - 4-Way Event, Style and Accuracy Landing - Style",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: "FAI mini-site",
            description: nil,
            documents: nil,
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17670",
            title: "2025 FAI World Drone Soccer Championships",
            location: "Shanghai",
            country: "CHN",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 15)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 18)) ?? Date(),
            eventType: .worldChampionship,
            sport: .aeromodelling,
            discipline: "F9 - Drone Sport - F9A - Drone Soccer",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "https://world-drone-soccer-championships.cn",
            faiMiniSiteURL: "https://fai.org/events/17670",
            description: nil,
            documents: ["Bulletin 1"],
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        ),
        AviationEvent(
            id: "17193",
            title: "2025 FAI F1D European Championships for Indoor Model Aircraft",
            location: "Slanic Prahova",
            country: "ROU",
            startDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 24)) ?? Date(),
            endDate: Calendar.current.date(from: DateComponents(year: 2025, month: 11, day: 27)) ?? Date(),
            eventType: .continentalChampionship,
            sport: .aeromodelling,
            discipline: "F1 - Free Flight - F1D (FF Indoor Aircraft)",
            classification: .cat1,
            organizer: "FAI Member of the Organising Country",
            websiteURL: "Organiser website",
            faiMiniSiteURL: nil,
            description: nil,
            documents: ["Bulletin 1"],
            contactPerson: nil,
            contactEmail: nil,
            contactPhone: nil,
            alternateDates: nil
        )
    ]
    
    static let mockAllEvents: [AviationEvent] = mockCurrentEvents + mockFAIChampionships
}
