import Foundation
import ComposableArchitecture

@DependencyClient
struct AviationRecordsClient {
    var loadRecords: @Sendable () async throws -> [AviationRecord]
    var loadRecordsByCategory: @Sendable (RecordCategory) async throws -> [AviationRecord]
    var loadHistoricalRecords: @Sendable () async throws -> [AviationRecord]
}

extension AviationRecordsClient: DependencyKey {
    static let liveValue = Self(
        loadRecords: { AviationRecordsClient.mockRecords },
        loadRecordsByCategory: { category in
            AviationRecordsClient.mockRecords.filter { $0.category == category }
        },
        loadHistoricalRecords: {
            AviationRecordsClient.mockRecords.filter { $0.category == .historical }
        }
    )
    
    static let testValue = Self(
        loadRecords: { [] },
        loadRecordsByCategory: { _ in [] },
        loadHistoricalRecords: { [] }
    )
}

extension DependencyValues {
    var aviationRecordsClient: AviationRecordsClient {
        get { self[AviationRecordsClient.self] }
        set { self[AviationRecordsClient.self] = newValue }
    }
}

extension AviationRecordsClient {
    static let mockRecords: [AviationRecord] = [
        AviationRecord(
            id: "fai_20919",
            title: "Acrobatic Longest sequence",
            description: "Parachuting G-1 acrobatic record",
            value: "12",
            unit: "grips",
            category: .parachuting,
            year: 2025,
            pilot: "USA Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Acrobatic Longest sequence",
            performance: "12 grips",
            date: "19 Aug 2025",
            claimant: "USA",
            status: "Ratified - current record",
            region: "North-American",
            faiId: "20919"
        ),
        AviationRecord(
            id: "fai_20912",
            title: "Free Distance around triangular course",
            description: "Hang Gliding and Paragliding O-3 distance record",
            value: "358.6",
            unit: "km",
            category: .hangGliding,
            year: 2025,
            pilot: "Edouard Potel",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Hang Gliding and Paragliding",
            faiSubClass: "O-3",
            recordType: "Free Distance around a triangular course",
            performance: "358,6 km",
            date: "18 Aug 2025",
            claimant: "Edouard Potel (FRA)",
            status: "Preliminary record claim received",
            region: "European",
            faiId: "20912"
        ),
        AviationRecord(
            id: "fai_20924",
            title: "Speed over Recognised Course",
            description: "Powered Aeroplanes C-1l speed record",
            value: "900.15",
            unit: "km/h",
            category: .speed,
            year: 2025,
            pilot: "Thomas Weston",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Powered Aeroplanes",
            faiSubClass: "C-1l",
            recordType: "Speed over a recognised course",
            performance: "900,15 km/h",
            date: "17 Aug 2025",
            claimant: "Thomas Weston (GBR)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20924"
        ),
        AviationRecord(
            id: "fai_20917",
            title: "Longest time",
            description: "Parachuting G-1 endurance record",
            value: "112.0",
            unit: "sec",
            category: .parachuting,
            year: 2025,
            pilot: "Alexey Galda",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Longest time",
            performance: "112,0 sec",
            date: "17 Aug 2025",
            claimant: "Alexey Galda (USA)",
            status: "Ratified - current record",
            region: "North-American",
            faiId: "20917"
        ),
        AviationRecord(
            id: "fai_20903",
            title: "Speed over Recognised Course",
            description: "Rotorcraft E-1c speed record",
            value: "48.00",
            unit: "km/h",
            category: .rotorcraft,
            year: 2025,
            pilot: "Owen J. Watkins",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Rotorcraft",
            faiSubClass: "E-1c",
            recordType: "Speed over a recognised course",
            performance: "48,00 km/h",
            date: "15 Aug 2025",
            claimant: "Owen J. Watkins (USA)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20903"
        ),
        AviationRecord(
            id: "fai_20907",
            title: "Absolute altitude",
            description: "Solar-Powered Aeroplanes CS altitude record",
            value: "9,640.00",
            unit: "m",
            category: .solarPowered,
            year: 2025,
            pilot: "Raphaël Domjan",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "CS (Solar-Powered Aeroplanes)",
            faiSubClass: "CS",
            recordType: "Absolute altitude",
            performance: "9 640,00 m",
            date: "12 Aug 2025",
            claimant: "Raphaël Domjan (SUI)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20907"
        ),
        AviationRecord(
            id: "fai_20880",
            title: "Straight Distance to a Goal",
            description: "Gliding DO distance record",
            value: "1,311.00",
            unit: "km",
            category: .gliding,
            year: 2025,
            pilot: "Jim Lee",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Gliding",
            faiSubClass: "DO",
            recordType: "Straight Distance to a Goal",
            performance: "1 311,00 km",
            date: "21 Jul 2025",
            claimant: "Jim Lee (USA)",
            status: "Preliminary record claim received",
            region: "North-American",
            faiId: "20880"
        ),
        AviationRecord(
            id: "fai_20886",
            title: "Speed in closed circuit competition",
            description: "Aeromodelling F3E speed record",
            value: "54.50",
            unit: "sec",
            category: .aeromodelling,
            year: 2025,
            pilot: "Mark de Groot",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Aeromodelling and Spacemodelling",
            faiSubClass: "F3E",
            recordType: "Speed in a closed circuit in competition (10 laps): F090",
            performance: "54,50 sec",
            date: "25 Jul 2025",
            claimant: "Mark de Groot (NED)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20886"
        ),
        AviationRecord(
            id: "fai_20976",
            title: "Speed over Recognised Course",
            description: "Powered Aeroplanes C-1l speed record",
            value: "844.73",
            unit: "km/h",
            category: .speed,
            year: 2025,
            pilot: "Dominic Rivers",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Powered Aeroplanes",
            faiSubClass: "C-1l",
            recordType: "Speed over a recognised course",
            performance: "844,73 km/h",
            date: "03 Sep 2025",
            claimant: "Dominic Rivers (GBR)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20976"
        ),
        AviationRecord(
            id: "fai_20973",
            title: "Speed over Commercial Airline Route",
            description: "Powered Aeroplanes C-1 speed record",
            value: "870.00",
            unit: "km/h",
            category: .speed,
            year: 2025,
            pilot: "Christopher R. Yakabe",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Powered Aeroplanes",
            faiSubClass: "C-1",
            recordType: "Speed over a Commercial Airline Route",
            performance: "870,00 km/h",
            date: "02 Sep 2025",
            claimant: "Christopher R. Yakabe (USA)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20973"
        ),
        AviationRecord(
            id: "fai_20972",
            title: "Speed over Commercial Airline Route",
            description: "Powered Aeroplanes C-1 speed record",
            value: "907.00",
            unit: "km/h",
            category: .speed,
            year: 2025,
            pilot: "Christopher R. Yakabe",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Powered Aeroplanes",
            faiSubClass: "C-1",
            recordType: "Speed over a Commercial Airline Route",
            performance: "907,00 km/h",
            date: "01 Sep 2025",
            claimant: "Christopher R. Yakabe (USA)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20972"
        ),
        AviationRecord(
            id: "fai_20965",
            title: "Maximum Vertical Speed without drogue",
            description: "Parachuting G-2 speed record",
            value: "555.23",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-2",
            recordType: "Maximum Vertical Speed without drogue",
            performance: "555,23 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "European",
            faiId: "20965"
        ),
        AviationRecord(
            id: "fai_20963",
            title: "Highest average speed - Mixed Team",
            description: "Parachuting G-1 team speed record",
            value: "487.91",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Netherlands Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed - Mixed Team",
            performance: "487,91 km/h",
            date: "29 Aug 2025",
            claimant: "Netherlands",
            status: "Ratified - current record",
            region: "European",
            faiId: "20963"
        ),
        AviationRecord(
            id: "fai_20962",
            title: "Highest overall average speed - Team",
            description: "Parachuting G-1 team speed record",
            value: "493.62",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Germany Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed - Team",
            performance: "493,62 km/h",
            date: "29 Aug 2025",
            claimant: "Germany",
            status: "Ratified - current record",
            region: "European",
            faiId: "20962"
        ),
        AviationRecord(
            id: "fai_20961",
            title: "Highest average speed - Team",
            description: "Parachuting G-1 team speed record",
            value: "498.96",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Germany Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed - Team",
            performance: "498,96 km/h",
            date: "29 Aug 2025",
            claimant: "Germany",
            status: "Ratified - current record",
            region: "European",
            faiId: "20961"
        ),
        AviationRecord(
            id: "fai_20960",
            title: "Highest overall average speed - Team",
            description: "Parachuting G-1 team speed record",
            value: "500.91",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Australia Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed - Team",
            performance: "500,91 km/h",
            date: "29 Aug 2025",
            claimant: "Australia",
            status: "Ratified - current record",
            region: "Oceanian",
            faiId: "20960"
        ),
        AviationRecord(
            id: "fai_20959",
            title: "Highest overall average speed - Team",
            description: "Parachuting G-1 team speed record",
            value: "500.91",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Australia Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed - Team",
            performance: "500,91 km/h",
            date: "29 Aug 2025",
            claimant: "Australia",
            status: "Ratified - current record",
            region: "World",
            faiId: "20959"
        ),
        AviationRecord(
            id: "fai_20954",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "465.29",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Ingrid van Deelen",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "465,29 km/h",
            date: "29 Aug 2025",
            claimant: "Ingrid van Deelen (NED)",
            status: "Ratified - current record",
            region: "European",
            faiId: "20954"
        ),
        AviationRecord(
            id: "fai_20952",
            title: "Highest average speed",
            description: "Parachuting G-1 individual speed record",
            value: "533.35",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Mervyn O'Connell",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed",
            performance: "533,35 km/h",
            date: "29 Aug 2025",
            claimant: "Mervyn O'Connell (AUS)",
            status: "Ratified - current record",
            region: "Oceanian",
            faiId: "20952"
        ),
        AviationRecord(
            id: "fai_20951",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "528.38",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Mervyn O'Connell",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "528,38 km/h",
            date: "29 Aug 2025",
            claimant: "Mervyn O'Connell (AUS)",
            status: "Ratified - current record",
            region: "Oceanian",
            faiId: "20951"
        ),
        AviationRecord(
            id: "fai_20950",
            title: "Highest average speed",
            description: "Parachuting G-1 individual speed record",
            value: "497.31",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Natisha Dingle",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed",
            performance: "497,31 km/h",
            date: "29 Aug 2025",
            claimant: "Natisha Dingle (AUS)",
            status: "Ratified - current record",
            region: "Oceanian",
            faiId: "20950"
        ),
        AviationRecord(
            id: "fai_20949",
            title: "Highest average speed",
            description: "Parachuting G-1 individual speed record",
            value: "528.54",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Niklas Daniel",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed",
            performance: "528,54 km/h",
            date: "29 Aug 2025",
            claimant: "Niklas Daniel (USA)",
            status: "Ratified - current record",
            region: "North-American",
            faiId: "20949"
        ),
        AviationRecord(
            id: "fai_20947",
            title: "Highest average speed",
            description: "Parachuting G-1 individual speed record",
            value: "539.51",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest average speed",
            performance: "539,51 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "World",
            faiId: "20947"
        ),
        AviationRecord(
            id: "fai_20946",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "536.75",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "536,75 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "European",
            faiId: "20946"
        ),
        AviationRecord(
            id: "fai_20945",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "536.75",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "536,75 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "World",
            faiId: "20945"
        ),
        AviationRecord(
            id: "fai_20942",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "536.75",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "536,75 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "European",
            faiId: "20942"
        ),
        AviationRecord(
            id: "fai_20941",
            title: "Highest overall average speed",
            description: "Parachuting G-1 individual speed record",
            value: "536.75",
            unit: "km/h",
            category: .parachuting,
            year: 2025,
            pilot: "Sebastián García Gutiérrez",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Highest overall average speed",
            performance: "536,75 km/h",
            date: "29 Aug 2025",
            claimant: "Sebastián García Gutiérrez (ESP)",
            status: "Ratified - current record",
            region: "World",
            faiId: "20941"
        ),
        AviationRecord(
            id: "fai_20933",
            title: "True altitude",
            description: "UAV altitude record",
            value: "4,584.19",
            unit: "m",
            category: .uav,
            year: 2025,
            pilot: "Lockheed Martin Aeronautics team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "U (Unmanned Aerial Vehicles (UAV",
            faiSubClass: "U-3",
            recordType: "True altitude",
            performance: "4 584,19 m",
            date: "21 Aug 2025",
            claimant: "Lockheed Martin Aeronautics team (USA)",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20933"
        ),
        AviationRecord(
            id: "fai_20925",
            title: "VFS Largest Formation Head Down",
            description: "Parachuting formation record",
            value: "174",
            unit: "skydivers",
            category: .parachuting,
            year: 2025,
            pilot: "Team/Crew",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-2",
            recordType: "VFS Largest Formation Head Down",
            performance: "174 skydivers",
            date: "22 Aug 2025",
            claimant: "Team/Crew",
            status: "Preliminary record claim received",
            region: "World",
            faiId: "20925"
        ),
        AviationRecord(
            id: "fai_20915",
            title: "Longest time",
            description: "Parachuting endurance record",
            value: "106.2",
            unit: "sec",
            category: .parachuting,
            year: 2025,
            pilot: "Farhan Raihan",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Longest time",
            performance: "106,2 sec",
            date: "20 Aug 2025",
            claimant: "Farhan Raihan (KUW)",
            status: "Ratified - current record",
            region: "Asian",
            faiId: "20915"
        ),
        AviationRecord(
            id: "fai_20920",
            title: "Acrobatic Longest sequence",
            description: "Parachuting acrobatic record",
            value: "10",
            unit: "grips",
            category: .parachuting,
            year: 2025,
            pilot: "Spain Team",
            aircraft: nil,
            location: nil,
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: nil,
            faiClass: "Parachuting",
            faiSubClass: "G-1",
            recordType: "Acrobatic Longest sequence",
            performance: "10 grips",
            date: "19 Aug 2025",
            claimant: "Spain",
            status: "Ratified - current record",
            region: "European",
            faiId: "20920"
        ),
        AviationRecord(
            id: "speed_1",
            title: "Fastest Aircraft",
            description: "Highest speed achieved by a manned aircraft",
            value: "7,274",
            unit: "km/h",
            category: .speed,
            year: 1967,
            pilot: "William J. Knight",
            aircraft: "North American X-15",
            location: "Edwards Air Force Base, USA",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "6,420 km/h (X-15, 1963)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "speed_2",
            title: "Fastest Operational Aircraft",
            description: "Highest speed achieved by an operational aircraft",
            value: "3,529",
            unit: "km/h",
            category: .speed,
            year: 1976,
            pilot: "Eldon W. Joersz",
            aircraft: "Lockheed SR-71 Blackbird",
            location: "Beale Air Force Base, USA",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "3,370 km/h (SR-71, 1974)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "speed_3",
            title: "Fastest Commercial Aircraft",
            description: "Highest speed achieved by a commercial passenger aircraft",
            value: "2,179",
            unit: "km/h",
            category: .speed,
            year: 2003,
            pilot: "Mike Bannister",
            aircraft: "Concorde",
            location: "London to New York",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "2,158 km/h (Concorde, 1996)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "altitude_1",
            title: "Highest Altitude",
            description: "Highest altitude achieved by a manned aircraft",
            value: "107,960",
            unit: "m",
            category: .altitude,
            year: 1963,
            pilot: "Joseph A. Walker",
            aircraft: "North American X-15",
            location: "Edwards Air Force Base, USA",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "95,936 m (X-15, 1962)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "altitude_2",
            title: "Highest Commercial Flight",
            description: "Highest altitude achieved by a commercial passenger aircraft",
            value: "18,288",
            unit: "m",
            category: .altitude,
            year: 2003,
            pilot: "Mike Bannister",
            aircraft: "Concorde",
            location: "Transatlantic Flight",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "17,700 m (Concorde, 1999)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "distance_1",
            title: "Longest Non-stop Flight",
            description: "Longest non-stop commercial flight",
            value: "21,602",
            unit: "km",
            category: .distance,
            year: 2005,
            pilot: "Captain Paul Stilwell",
            aircraft: "Boeing 777-200LR",
            location: "Hong Kong to London",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "20,044 km (Boeing 777-200LR, 2005)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "distance_2",
            title: "Longest Endurance Flight",
            description: "Longest continuous flight without refueling",
            value: "64",
            unit: "days",
            category: .endurance,
            year: 1958,
            pilot: "Robert Timm & John Cook",
            aircraft: "Cessna 172",
            location: "Las Vegas, USA",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "50 days (Cessna 172, 1958)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "historical_1",
            title: "First Powered Flight",
            description: "First controlled, sustained flight of a powered aircraft",
            value: "12",
            unit: "seconds",
            category: .historical,
            year: 1903,
            pilot: "Orville Wright",
            aircraft: "Wright Flyer",
            location: "Kitty Hawk, North Carolina, USA",
            imageURL: nil,
            isCurrentRecord: false,
            previousRecord: nil,
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "historical_2",
            title: "First Transatlantic Flight",
            description: "First non-stop transatlantic flight",
            value: "33.5",
            unit: "hours",
            category: .historical,
            year: 1927,
            pilot: "Charles Lindbergh",
            aircraft: "Spirit of St. Louis",
            location: "New York to Paris",
            imageURL: nil,
            isCurrentRecord: false,
            previousRecord: nil,
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "historical_3",
            title: "First Woman to Cross Atlantic",
            description: "First woman to fly solo across the Atlantic Ocean",
            value: "14.75",
            unit: "hours",
            category: .historical,
            year: 1932,
            pilot: "Amelia Earhart",
            aircraft: "Lockheed Vega 5B",
            location: "Newfoundland to Ireland",
            imageURL: nil,
            isCurrentRecord: false,
            previousRecord: nil,
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "military_1",
            title: "Fastest Military Aircraft",
            description: "Highest speed achieved by a military aircraft",
            value: "3,529",
            unit: "km/h",
            category: .military,
            year: 1976,
            pilot: "Eldon W. Joersz",
            aircraft: "Lockheed SR-71 Blackbird",
            location: "Beale Air Force Base, USA",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "3,370 km/h (SR-71, 1974)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "payload_1",
            title: "Heaviest Aircraft",
            description: "Heaviest aircraft ever built",
            value: "640",
            unit: "tons",
            category: .payload,
            year: 1988,
            pilot: "Viktor Tolmachev",
            aircraft: "Antonov An-225 Mriya",
            location: "Kiev, Ukraine",
            imageURL: nil,
            isCurrentRecord: true,
            previousRecord: "285 tons (Boeing 747, 1970)",
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        ),
        AviationRecord(
            id: "experimental_1",
            title: "First Supersonic Flight",
            description: "First aircraft to break the sound barrier",
            value: "1,225",
            unit: "km/h",
            category: .experimental,
            year: 1947,
            pilot: "Chuck Yeager",
            aircraft: "Bell X-1",
            location: "Edwards Air Force Base, USA",
            imageURL: nil,
            isCurrentRecord: false,
            previousRecord: nil,
            faiClass: nil,
            faiSubClass: nil,
            recordType: nil,
            performance: nil,
            date: nil,
            claimant: nil,
            status: nil,
            region: nil,
            faiId: nil
        )
    ]
}
